language: go

go:
  - 1.7
  - 1.8
  - tip

sudo: false

install:
  - go get github.com/zieckey/goini
  - go get github.com/unrolled/render
  - go get github.com/go-playground/log
  - go get github.com/go-playground/ansi
  - go get gopkg.in/go-playground/assert.v1
  
script:
  - go test


