language: go

go:
  - 1.7
  - 1.8
  - tip

sudo: false

install:
    # - sudo apt-get install sshpass
  - go get github.com/zieckey/goini
  - go get github.com/unrolled/render
  - go get github.com/go-playground/log
  - go get github.com/go-playground/ansi
  - go get gopkg.in/go-playground/assert.v1
  
script:
  - go test -v ./...
  - go build -v 
  - sshpass -p $DAOCLOUD_SSH_PASS ssh -o StrictHostKeyChecking=no $DAOCLOUD_SSH_URL "[ -f nanoweb ] && rm nanoweb "
  - sshpass -p $DAOCLOUD_SSH_PASS scp -o stricthostkeychecking=no nanoweb $DAOCLOUD_SSH_RUL:/home/ubuntu
  - sshpass -p $DAOCLOUD_SSH_PASS ssh -o StrictHostKeyChecking=no $DAOCLOUD_SSH_URL "NANOWEB_STATUS=`ps -A | grep nanoweb | wc -l` && [ $NANOWEB_STATUS -eq 1 ] && killall nanoweb && ./nanoweb&"


